/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber.tugas;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Rusfandi
 */
public class ManajemenNasabahFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManajemenNasabagFrame
     */
    public ManajemenNasabahFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        marriedCheckBox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        nomorHpTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        idNasabahTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nomorTeleponTextField = new javax.swing.JTextField();
        alamatTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cariTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Gender");

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel4.setText("Married");

        jLabel5.setText("Nomor Hp");

        jLabel6.setText("Age");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Nasabah", "Nama Nasabah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Reload Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Id Nasabah");

        idNasabahTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idNasabahTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Nomor Telepon");

        jLabel8.setText("Alamat");

        cariTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTextFieldActionPerformed(evt);
            }
        });
        cariTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(28, 28, 28)
                                .addComponent(cariTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                .addComponent(nameTextField)
                                .addComponent(idNasabahTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(marriedCheckBox)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nomorHpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alamatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomorTeleponTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cariTextField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(idNasabahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomorHpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(nomorTeleponTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(marriedCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showPeople() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        List<DataNasabah> dataNasabah = getDataFromFile("C:\\JAVA_LATIHAN\\ManajemenNasabah.txt");
        model.setRowCount(0);
        Object[] row = new Object[2];
        for (DataNasabah dNasabah : dataNasabah) {
            row[0] = dNasabah.getKode();
            row[1] = dNasabah.getName();
//            row[2] = dNasabah.getGender();
//            row[3] = dNasabah.getMaried();
//            row[4] = dNasabah.getAge();
//            row[5] = dNasabah.getNomorHpNasabah();
//            row[6] = dNasabah.getNomorTeleponNasabah();
//            row[7] = dNasabah.getAlamatNasabah();

            model.addRow(row);
        }

        ListSelectionModel rowModel = jTable1.getSelectionModel();
        rowModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int i = jTable1.getSelectedRow();
                    String id = (String) model.getValueAt(i, 0);//ambil velue row i 
                    idNasabahTextField.setText(id);
                    String nama = (String) model.getValueAt(i, 1);//ambil velue row i 
                    nameTextField.setText(nama);
//                    String gender = (String) model.getValueAt(i, 2);//ambil velue row i 
//                    genderComboBox.setSelectedItem(gender);
//                    Boolean maried = (Boolean) model.getValueAt(i, 3);//ambil velue row i 
//                    marriedCheckBox.setSelected(maried);
//                    Integer age = (Integer) model.getValueAt(i, 4);
//                    String umur = String.valueOf(age);
//                    ageTextField.setText(umur);
//                    String hp = (String) model.getValueAt(i, 5);//ambil velue row i 
//                    nomorHpTextField.setText(hp);
//                    String telepon = (String) model.getValueAt(i, 6);//ambil velue row i 
//                    nomorTeleponTextField.setText(telepon);
                   //String alamat = (String) model.getValueAt(i, 7);//ambil velue row i 
                    alamatTextField.setText(dataNasabah.get(i).getAlamatNasabah());

//                List<DataNasabah> dataNasabah = getDataFromFile("C:\\JAVA_LATIHAN\\ManajemenNasabah.txt");
//                    for (DataNasabah dNasabah : dataNasabah) {
////
                        Boolean maried = dataNasabah.get(i).getMaried();
                        marriedCheckBox.setSelected(maried);
                        Integer age = dataNasabah.get(i).getAge();
                        String umur = String.valueOf(age);
                        genderComboBox.setSelectedItem(dataNasabah.get(i).getGender());
                        ageTextField.setText(umur);
                        String hp = dataNasabah.get(i).getNomorHpNasabah();//ambil velue row i 
                        nomorHpTextField.setText(hp);
                        String telepon = dataNasabah.get(i).getNomorTeleponNasabah();//ambil velue row i 
                        nomorTeleponTextField.setText(telepon);
//                        String alamat = dNasabah.getAlamatNasabah();//ambil velue row i 
//                        alamatTextArea.setText(alamat);
////
//                    }
                    System.out.println("row dipilih");
                }
            }

        });

    }
    
//    private void showPeople(){
//        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//        List<DataNasabah> dataNasabah = getDataFromFile("C:\\JAVA_LATIHAN\\ManajemenNAsabah.txt");
//        
//    }
    
    private List<DataNasabah> getDataFromFile(String filename) {
        FileReader fileReader = null;
        try {
            List<DataNasabah> dataNasabah = new ArrayList<>();
            File file = new File(filename);
            fileReader = new FileReader(file); //mencari file
            BufferedReader reader = new BufferedReader(fileReader);// untuk memanggil filereader/membaca file
            String line = null;
            while ((line = reader.readLine()) != null) {
                System.out.println(line);
                //Split line assign ke strig array
                String[] splitLine = line.split(",");
                //buat objek questionmodel, array idx 0 kata dasar, idx 1 untuk petunjuk
                DataNasabah wm = new DataNasabah(splitLine[0], splitLine[1].trim(), splitLine[2].trim(), Boolean.parseBoolean(splitLine[3].trim()), Integer.parseInt(splitLine[4].trim()), splitLine[5].trim(), splitLine[6].trim(), splitLine[7].trim());
                //DataNasabah wm = new DataNasabah(splitLine[0], splitLine[1]);                
                // add ke question collection
                dataNasabah.add(wm);
            }
           // Collections.sort(dataNasabah);
            //periksa ukuran question
            System.out.println("\nJumlah Pertanyaan Dalam Collection : " + dataNasabah.size() + "\n");
            //iterasi collection
//        for (DataNasabah q : dataNasabah) {
//      
//        }
            return dataNasabah;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ManajemenNasabahFrame.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("File Tidak Ditemukan");
        } catch (IOException ex) {
            Logger.getLogger(ManajemenNasabahFrame.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Kemungkinan File Rusak");
        } finally {
            try {
                fileReader.close();
            } catch (IOException ex) {
                Logger.getLogger(ManajemenNasabahFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return null;
    


                
    }
    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void idNasabahTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idNasabahTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idNasabahTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        showPeople();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cariTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariTextFieldActionPerformed

    private void cariTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariTextFieldKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String search = cariTextField.getText().toString();
        TableRowSorter<TableModel>ts= new TableRowSorter(model);
        jTable1.setRowSorter(ts);
        ts.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_cariTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManajemenNasabahFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManajemenNasabahFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManajemenNasabahFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManajemenNasabahFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManajemenNasabahFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTextField;
    private javax.swing.JTextField alamatTextField;
    private javax.swing.JTextField cariTextField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JTextField idNasabahTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox marriedCheckBox;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField nomorHpTextField;
    private javax.swing.JTextField nomorTeleponTextField;
    // End of variables declaration//GEN-END:variables
}
